# -*- coding: utf-8 -*-
"""Kelompok4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCL0Vb4xs1L0RI6VYMDcJzkkkWJc6mQy
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns
import io

# Konfigurasi halaman
st.set_page_config(
    page_title="KNN Regresi - Prediksi Omset UMKM",
    page_icon="📊",
    layout="wide"
)

# CSS untuk styling
st.markdown("""
    <style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #1f77b4;
        text-align: center;
        margin-bottom: 1rem;
    }
    .sub-header {
        font-size: 1.2rem;
        color: #666;
        text-align: center;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 10px;
        text-align: center;
    }
    </style>
""", unsafe_allow_html=True)

# Header
st.markdown('<div class="main-header">📊 KNN Regresi - Prediksi Omset UMKM</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Analisis dan Prediksi Omset UMKM berdasarkan berbagai fitur</div>', unsafe_allow_html=True)

# Sidebar
st.sidebar.header("⚙️ Pengaturan Model")

# Parameter KNN
k_value = st.sidebar.slider("Nilai K (Jumlah Tetangga)", 1, 50, 5, 1)
test_size = st.sidebar.slider("Ukuran Data Uji (Test Size)", 0.1, 0.5, 0.2, 0.05)

# Pilihan fitur
st.sidebar.subheader("📋 Pilih Fitur untuk Prediksi")
use_all_features = st.sidebar.checkbox("Gunakan Semua Fitur", value=True)

# Load data
@st.cache_data
def load_data():
    # Data dari file yang diberikan
    data = """
id_umkm,nama_usaha,jenis_usaha,tenaga_kerja_perempuan,tenaga_kerja_laki_laki,aset,omset,marketplace,kapasitas_produksi,status_legalitas,tahun_berdiri,laba,biaya_karyawan,jumlah_pelanggan
28828567,UD. Alif Pamungkas,Kesehatan,1,56,5497149,3347794,Tokopedia,479,Belum Terdaftar,2015,-2149355,171000000,479
28828568,UD. Zidanar Panji,Perdagangan,5,44,7398384,39969661,Bukalapak,464,Terdaftar,2014,32571277,147000000,464
28828569,UD. Winda Jayengprana,unknown,74,51,8881762,25253355,Website Sendiri,383,Belum Terdaftar,2000,16371593,375000000,383
28828570,UD. Damaris Satria,Jasa,89,5,9576178,20700389,Website Sendiri,986,Belum Terdaftar,2003,11124211,282000000,986
28828571,UD. Qasya Wiratama,Jasa,91,59,9456853,4820810,Lazada,314,Belum Terdaftar,2002,-4636043,450000000,314
"""
    # Membaca data dari file yang diupload atau menggunakan data yang sudah ada
    # Karena data sangat besar, kita akan gunakan pendekatan dengan mengupload file

    return None

# Upload file
uploaded_file = st.file_uploader("📂 Upload file CSV (datase_usaha.csv)", type=['csv'])

if uploaded_file is not None:
    # Baca data
    df = pd.read_csv(uploaded_file)

    # Tampilkan info data
    st.subheader("📋 Preview Data")
    st.write(f"Total data: {len(df)} baris, {len(df.columns)} kolom")
    st.dataframe(df.head(10))

    # Preprocessing
    @st.cache_data
    def preprocess_data(df):
        df_clean = df.copy()

        # Handle missing values
        df_clean = df_clean.replace('unknown', np.nan)
        df_clean = df_clean.replace('', np.nan)

        # Konversi kolom numerik
        numeric_cols = ['tenaga_kerja_perempuan', 'tenaga_kerja_laki_laki', 'aset',
                        'omset', 'kapasitas_produksi', 'tahun_berdiri', 'laba',
                        'biaya_karyawan', 'jumlah_pelanggan']

        for col in numeric_cols:
            if col in df_clean.columns:
                df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

        # Drop rows dengan target NaN
        df_clean = df_clean.dropna(subset=['omset'])

        # Handle missing values untuk fitur
        for col in numeric_cols:
            if col in df_clean.columns and col != 'omset':
                df_clean[col] = df_clean[col].fillna(df_clean[col].median())

        # Encode categorical
        cat_cols = ['jenis_usaha', 'marketplace', 'status_legalitas']
        label_encoders = {}
        for col in cat_cols:
            if col in df_clean.columns:
                le = LabelEncoder()
                # Handle missing values
                df_clean[col] = df_clean[col].fillna('Unknown')
                df_clean[col] = le.fit_transform(df_clean[col].astype(str))
                label_encoders[col] = le

        return df_clean, label_encoders

    df_clean, label_encoders = preprocess_data(df)

    # Pilih fitur
    st.subheader("🎯 Pemilihan Fitur")

    numeric_cols = ['tenaga_kerja_perempuan', 'tenaga_kerja_laki_laki', 'aset',
                    'kapasitas_produksi', 'tahun_berdiri', 'laba',
                    'biaya_karyawan', 'jumlah_pelanggan']
    cat_cols = ['jenis_usaha', 'marketplace', 'status_legalitas']

    available_cols = [col for col in numeric_cols + cat_cols if col in df_clean.columns]

    if use_all_features:
        selected_features = available_cols
    else:
        selected_features = st.multiselect(
            "Pilih fitur untuk prediksi:",
            available_cols,
            default=available_cols[:5]
        )

    if selected_features:
        # Persiapan data untuk modeling
        X = df_clean[selected_features]
        y = df_clean['omset']

        # Standarisasi fitur numerik
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        # Split data
        X_train, X_test, y_train, y_test = train_test_split(
            X_scaled, y, test_size=test_size, random_state=42
        )

        # Train KNN model
        knn = KNeighborsRegressor(n_neighbors=k_value, weights='distance')
        knn.fit(X_train, y_train)

        # Prediksi
        y_pred_train = knn.predict(X_train)
        y_pred_test = knn.predict(X_test)

        # Metrik evaluasi
        rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
        rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))
        r2_train = r2_score(y_train, y_pred_train)
        r2_test = r2_score(y_test, y_pred_test)
        mae_train = mean_absolute_error(y_train, y_pred_train)
        mae_test = mean_absolute_error(y_test, y_pred_test)

        # Tampilkan metrik
        st.subheader("📊 Evaluasi Model")

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("RMSE Train", f"{rmse_train:,.0f}")
        with col2:
            st.metric("RMSE Test", f"{rmse_test:,.0f}")
        with col3:
            st.metric("R² Train", f"{r2_train:.4f}")
        with col4:
            st.metric("R² Test", f"{r2_test:.4f}")

        col5, col6 = st.columns(2)
        with col5:
            st.metric("MAE Train", f"{mae_train:,.0f}")
        with col6:
            st.metric("MAE Test", f"{mae_test:,.0f}")

        # Visualisasi
        st.subheader("📈 Visualisasi Hasil")

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # Plot prediksi vs aktual - Training
        axes[0].scatter(y_train, y_pred_train, alpha=0.5)
        axes[0].plot([y_train.min(), y_train.max()], [y_train.min(), y_train.max()], 'r--', lw=2)
        axes[0].set_xlabel('Aktual')
        axes[0].set_ylabel('Prediksi')
        axes[0].set_title(f'Training Set (R² = {r2_train:.4f})')

        # Plot prediksi vs aktual - Testing
        axes[1].scatter(y_test, y_pred_test, alpha=0.5)
        axes[1].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
        axes[1].set_xlabel('Aktual')
        axes[1].set_ylabel('Prediksi')
        axes[1].set_title(f'Testing Set (R² = {r2_test:.4f})')

        plt.tight_layout()
        st.pyplot(fig)

        # Distribusi residual
        st.subheader("📊 Distribusi Residual")

        fig2, axes2 = plt.subplots(1, 2, figsize=(14, 5))

        residuals_train = y_train - y_pred_train
        residuals_test = y_test - y_pred_test

        axes2[0].hist(residuals_train, bins=30, alpha=0.7, color='blue', edgecolor='black')
        axes2[0].axvline(x=0, color='red', linestyle='--')
        axes2[0].set_xlabel('Residual')
        axes2[0].set_ylabel('Frekuensi')
        axes2[0].set_title(f'Residual Training (Mean = {residuals_train.mean():.0f})')

        axes2[1].hist(residuals_test, bins=30, alpha=0.7, color='green', edgecolor='black')
        axes2[1].axvline(x=0, color='red', linestyle='--')
        axes2[1].set_xlabel('Residual')
        axes2[1].set_ylabel('Frekuensi')
        axes2[1].set_title(f'Residual Testing (Mean = {residuals_test.mean():.0f})')

        plt.tight_layout()
        st.pyplot(fig2)

        # Prediksi baru
        st.subheader("🔮 Prediksi Omset UMKM")
        st.write("Masukkan data UMKM untuk memprediksi omset:")

        # Input fitur
        col_inputs = st.columns(4)
        input_values = {}

        for idx, col_name in enumerate(selected_features):
            col_idx = idx % 4
            with col_inputs[col_idx]:
                if col_name in numeric_cols:
                    # Ambil median untuk default
                    default_val = float(df_clean[col_name].median())
                    input_values[col_name] = st.number_input(
                        f"{col_name.replace('_', ' ').title()}",
                        value=default_val,
                        step=100000.0 if col_name in ['aset', 'omset', 'laba', 'biaya_karyawan'] else 1.0,
                        format="%.0f"
                    )
                else:
                    # Untuk categorical
                    unique_vals = sorted(df[col_name].dropna().unique())
                    default_idx = 0
                    input_values[col_name] = st.selectbox(
                        f"{col_name.replace('_', ' ').title()}",
                        unique_vals,
                        index=default_idx
                    )

        if st.button("🔮 Prediksi Omset", type="primary"):
            # Prepare input untuk prediksi
            input_array = []
            for col_name in selected_features:
                if col_name in cat_cols:
                    # Encode categorical
                    val = input_values[col_name]
                    if val in label_encoders[col_name].classes_:
                        encoded = label_encoders[col_name].transform([val])[0]
                    else:
                        encoded = 0
                    input_array.append(encoded)
                else:
                    input_array.append(input_values[col_name])

            # Scale dan prediksi
            input_scaled = scaler.transform([input_array])
            prediction = knn.predict(input_scaled)[0]

            st.success(f"💰 Prediksi Omset: Rp {prediction:,.0f}")

            # Tampilkan informasi tambahan
            st.info(f"""
            **Informasi Prediksi:**
            - Menggunakan K = {k_value} tetangga terdekat
            - Fitur yang digunakan: {', '.join(selected_features)}
            - Akurasi Model (R²): {r2_test:.4f}
            """)

        # Feature importance (berdasarkan koefisien variasi)
        st.subheader("📊 Pentingnya Fitur")

        # Hitung pengaruh fitur (standar deviasi dari prediksi saat fitur divariasi)
        feature_importance = {}
        X_mean = X_scaled.mean(axis=0)

        for idx, col_name in enumerate(selected_features):
            # Buat data dengan satu fitur divariasi
            X_var = np.tile(X_mean, (100, 1))
            X_var[:, idx] = np.linspace(-3, 3, 100)
            pred_var = knn.predict(X_var)
            feature_importance[col_name] = pred_var.std()

        # Plot
        fig3, ax3 = plt.subplots(figsize=(10, 6))
        sorted_features = sorted(feature_importance.items(), key=lambda x: x[1], reverse=True)
        names = [x[0] for x in sorted_features]
        values = [x[1] for x in sorted_features]

        ax3.barh(names, values)
        ax3.set_xlabel('Pengaruh (Standar Deviasi Prediksi)')
        ax3.set_title('Pentingnya Fitur dalam Model KNN')
        plt.tight_layout()
        st.pyplot(fig3)

        # Download prediksi
        st.subheader("📥 Download Hasil Prediksi")

        # Buat dataset dengan prediksi untuk semua data
        all_pred = knn.predict(X_scaled)
        df_results = df_clean.copy()
        df_results['prediksi_omset'] = all_pred

        csv = df_results[['nama_usaha', 'omset', 'prediksi_omset']].to_csv(index=False)
        st.download_button(
            label="📥 Download CSV",
            data=csv,
            file_name="prediksi_omset_knn.csv",
            mime="text/csv"
        )

        # Analisis tambahan - Hubungan K dengan performa
        st.subheader("🔍 Analisis Nilai K")

        k_values = range(1, min(50, len(X_train) // 5 + 1))
        train_scores = []
        test_scores = []

        for k in k_values:
            knn_temp = KNeighborsRegressor(n_neighbors=k, weights='distance')
            knn_temp.fit(X_train, y_train)
            train_scores.append(knn_temp.score(X_train, y_train))
            test_scores.append(knn_temp.score(X_test, y_test))

        fig4, ax4 = plt.subplots(figsize=(10, 6))
        ax4.plot(k_values, train_scores, label='Training R²', marker='o')
        ax4.plot(k_values, test_scores, label='Testing R²', marker='s')
        ax4.axvline(x=k_value, color='red', linestyle='--', label=f'K = {k_value}')
        ax4.set_xlabel('Nilai K')
        ax4.set_ylabel('R² Score')
        ax4.set_title('Performa Model terhadap Nilai K')
        ax4.legend()
        ax4.grid(True, alpha=0.3)
        plt.tight_layout()
        st.pyplot(fig4)

    else:
        st.warning("⚠️ Silakan pilih setidaknya satu fitur untuk prediksi.")
else:
    st.info("👈 Silakan upload file CSV 'datase_usaha.csv' di sidebar untuk memulai.")

    # Tampilkan contoh
    with st.expander("📖 Format Data yang Diharapkan"):
        st.markdown("""
        File CSV harus memiliki kolom-kolom berikut:
        - **id_umkm**: ID unik UMKM
        - **nama_usaha**: Nama usaha
        - **jenis_usaha**: Kategori usaha (Kesehatan, Perdagangan, Jasa, dll)
        - **tenaga_kerja_perempuan**: Jumlah tenaga kerja perempuan
        - **tenaga_kerja_laki_laki**: Jumlah tenaga kerja laki-laki
        - **aset**: Nilai aset (dalam Rupiah)
        - **omset**: Nilai omset (target prediksi)
        - **marketplace**: Platform marketplace yang digunakan
        - **kapasitas_produksi**: Kapasitas produksi
        - **status_legalitas**: Status legalitas (Terdaftar/Belum Terdaftar)
        - **tahun_berdiri**: Tahun berdiri usaha
        - **laba**: Laba usaha
        - **biaya_karyawan**: Biaya karyawan
        - **jumlah_pelanggan**: Jumlah pelanggan
        """)

st.markdown("---")
st.markdown("""
<div style="text-align: center; color: #666; font-size: 0.9rem;">
    Aplikasi KNN Regresi untuk Prediksi Omset UMKM | Dibuat dengan Streamlit
</div>
""", unsafe_allow_html=True)